{"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP"]]},"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"roleHeading":"Class","platforms":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false,"unavailable":false}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"title":"PushwooshVoIPImplementation","modules":[{"name":"PushwooshVoIP"}]},"abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"identifier":{"url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didActivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didDeactivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2c89a","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2ig32","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-440b5","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-6b5ut","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-79gr4","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-8zhob","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidBegin(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidReset(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didInvalidatePushTokenFor:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didUpdate:for:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/delegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/shared"],"title":"Type Properties","anchor":"Type-Properties"},{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/initializeVoIP(_:ringtoneSound:handleTypes:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setVoIPToken(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/voip()"],"title":"Type Methods","anchor":"Type-Methods"},{"generated":true,"identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/PWVoIP-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PushwooshVoIPImplementation) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)CXProviderDelegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject","doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)PKPushRegistryDelegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/@M@PushwooshBridge@objc(pl)PWVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/s7CVarArgP","doc:\/\/com.pushwoosh.PushwooshVoIP\/s28CustomDebugStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshVoIP\/s23CustomStringConvertibleP","doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ","doc:\/\/com.pushwoosh.PushwooshVoIP\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/shared":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/shared","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation","kind":"typeIdentifier","text":"PushwooshVoIPImplementation"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/shared","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"abstract":[{"text":"Shared singleton instance.","type":"text"}],"type":"topic"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/providerDidReset(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerDidReset"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"text":")","kind":"text"}],"title":"providerDidReset(_:)","navigatorTitle":[{"text":"providerDidReset:","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/providerdidreset(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidReset(_:)","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SQ"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","kind":"symbol","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"role":"symbol","abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"title":"PushwooshVoIPImplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setPushwooshVoIPAppId(_:)":{"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)","navigatorTitle":[{"kind":"identifier","text":"setPushwooshVoIPAppId:"}],"abstract":[{"type":"text","text":"Sets the Pushwoosh VoIP Application Code."}],"title":"setPushwooshVoIPAppId(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/init":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/init","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/init","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-8zhob":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-8zhob","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-8zhob","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:performSetHeldCallAction:"}],"abstract":[],"title":"provider(_:perform:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetHeldCallAction","text":"CXSetHeldCallAction"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/delegate":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/delegate","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/delegate","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"abstract":[{"text":"The delegate that receives VoIP call events.","type":"text"}],"title":"delegate","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AnyObject","kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta"},{"text":"?","kind":"text"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-6b5ut":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-6b5ut","navigatorTitle":[{"kind":"identifier","text":"provider:performEndCallAction:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXEndCallAction","text":"CXEndCallAction"},{"kind":"text","text":")"}],"title":"provider(_:perform:)","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-6b5ut"},"doc://com.pushwoosh.PushwooshVoIP/@M@PushwooshBridge@objc(pl)PWVoIP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/@M@PushwooshBridge@objc(pl)PWVoIP","title":"PWVoIP"},"doc://com.pushwoosh.PushwooshVoIP/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/initializeVoIP(_:ringtoneSound:handleTypes:)":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/initializevoip(_:ringtonesound:handletypes:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/initializeVoIP(_:ringtoneSound:handleTypes:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeVoIP:ringtoneSound:handleTypes:"}],"abstract":[{"text":"Initializes the VoIP module with CallKit configuration.","type":"text"}],"title":"initializeVoIP(_:ringtoneSound:handleTypes:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeVoIP"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ringtoneSound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handleTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didInvalidatePushTokenFor:)":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didinvalidatepushtokenfor:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didInvalidatePushTokenFor:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didInvalidatePushTokenForType:"}],"abstract":[],"title":"pushRegistry(_:didInvalidatePushTokenFor:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushRegistry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didInvalidatePushTokenFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType","text":"PKPushType"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:didDeactivate:)":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:diddeactivate:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didDeactivate:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:didDeactivateAudioSession:"}],"abstract":[],"title":"provider(_:didDeactivate:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeactivate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/SH","title":"Swift.Hashable"},"doc://com.pushwoosh.PushwooshVoIP/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pushwoosh.PushwooshVoIP/objc(pl)PKPushRegistryDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)PKPushRegistryDelegate","title":"PKPushRegistryDelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didreceiveincomingpushwith:for:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pushRegistry","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKPushRegistry","kind":"typeIdentifier","text":"PKPushRegistry"},{"kind":"text","text":", "},{"text":"didReceiveIncomingPushWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKPushPayload","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushPayload"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@PKPushType","kind":"typeIdentifier","text":"PKPushType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"pushRegistry(_:didReceiveIncomingPushWith:for:completion:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setVoIPToken(_:)":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setvoiptoken(_:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setVoIPToken(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setVoIPToken:"}],"abstract":[{"text":"Sets the VoIP push token manually.","type":"text"}],"title":"setVoIPToken(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVoIPToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:didActivate:)":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:didactivate:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didActivate:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:didActivateAudioSession:"}],"abstract":[],"title":"provider(_:didActivate:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didActivate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/voip()":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/voip()","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/voip()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"voip"}],"abstract":[{"text":"Returns the VoIP implementation class.","type":"text"}],"title":"voip()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"voip"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}]},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-2ig32":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-2ig32","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2ig32","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:performStartCallAction:"}],"abstract":[],"title":"provider(_:perform:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction","text":"CXStartCallAction"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/objc(pl)CXProviderDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)CXProviderDelegate","title":"CXProviderDelegate"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-79gr4":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-79gr4","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-79gr4","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:performSetMutedCallAction:"}],"abstract":[],"title":"provider(_:perform:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXSetMutedCallAction","text":"CXSetMutedCallAction"},{"kind":"text","text":")"}]},"doc://com.pushwoosh.PushwooshVoIP/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-440b5":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CXAnswerCallAction","preciseIdentifier":"c:objc(cs)CXAnswerCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"provider(_:perform:)","navigatorTitle":[{"text":"provider:performAnswerCallAction:","kind":"identifier"}],"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-440b5","role":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-440b5","kind":"symbol"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/providerDidBegin(_:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"providerDidBegin:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidBegin(_:)","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/providerdidbegin(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerDidBegin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":")"}],"title":"providerDidBegin(_:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/pushRegistry(_:didUpdate:for:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"pushRegistry:didUpdatePushCredentials:forType:"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didUpdate:for:)","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pushregistry(_:didupdate:for:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushRegistry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushRegistry","text":"PKPushRegistry"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPushCredentials","text":"PKPushCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@PKPushType","text":"PKPushType"},{"kind":"text","text":")"}],"title":"pushRegistry(_:didUpdate:for:)"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-2c89a":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"provider:performPlayDTMFCallAction:","kind":"identifier"}],"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2c89a","type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-2c89a","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"perform"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXPlayDTMFCallAction","text":"CXPlayDTMFCallAction"},{"text":")","kind":"text"}],"title":"provider(_:perform:)"},"doc://com.pushwoosh.PushwooshVoIP/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject","title":"NSObject"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/PWVoIP-Implementations":{"type":"topic","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/pwvoip-implementations","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/PWVoIP-Implementations","kind":"article","abstract":[],"title":"PWVoIP Implementations","role":"collectionGroup"},"doc://com.pushwoosh.PushwooshVoIP/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"14.0","beta":false}]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PushwooshVoIPImplementation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/init","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didActivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:didDeactivate:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2c89a","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2ig32","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-440b5","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-6b5ut","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-79gr4","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-8zhob","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidBegin(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/providerDidReset(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didInvalidatePushTokenFor:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didReceiveIncomingPushWith:for:completion:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/pushRegistry(_:didUpdate:for:)"],"generated":true,"anchor":"Instance-Methods"},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/delegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/shared"],"generated":true},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/initializeVoIP(_:ringtoneSound:handleTypes:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setVoIPToken(_:)","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/voip()"],"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)CXProviderDelegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/objc(pl)PKPushRegistryDelegate","doc:\/\/com.pushwoosh.PushwooshVoIP\/@M@PushwooshBridge@objc(pl)PWVoIP"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushwooshVoIPImplementation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1shared\/title","op":"replace","value":"shared"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1shared\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]},{"value":"providerDidReset:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1providerDidReset(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"providerDidReset:"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1providerDidReset(_:)\/fragments","op":"replace"},{"value":"PushwooshVoIPImplementation","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/navigatorTitle","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"value":"setPushwooshVoIPAppId:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setPushwooshVoIPAppId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-8zhob\/title","value":"provider:performSetHeldCallAction:"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:performSetHeldCallAction:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-8zhob\/fragments","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1delegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"value":"provider:performEndCallAction:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-6b5ut\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"provider:performEndCallAction:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-6b5ut\/fragments","op":"replace"},{"value":"initializeVoIP:ringtoneSound:handleTypes:","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1initializeVoIP(_:ringtoneSound:handleTypes:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1initializeVoIP(_:ringtoneSound:handleTypes:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initializeVoIP:ringtoneSound:handleTypes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didInvalidatePushTokenFor:)\/title","value":"pushRegistry:didInvalidatePushTokenForType:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didInvalidatePushTokenFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pushRegistry:didInvalidatePushTokenForType:"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didDeactivate:)\/title","op":"replace","value":"provider:didDeactivateAudioSession:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didDeactivate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"provider:didDeactivateAudioSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)\/title","value":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didReceiveIncomingPushWith:for:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setVoIPToken(_:)\/title","value":"setVoIPToken:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setVoIPToken(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setVoIPToken:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didActivate:)\/title","value":"provider:didActivateAudioSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:didActivate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:didActivateAudioSession:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1voip()\/title","value":"voip"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1voip()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"voip","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2ig32\/title","value":"provider:performStartCallAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2ig32\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:performStartCallAction:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-79gr4\/title","value":"provider:performSetMutedCallAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-79gr4\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:performSetMutedCallAction:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-440b5\/title","value":"provider:performAnswerCallAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-440b5\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:performAnswerCallAction:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1providerDidBegin(_:)\/title","value":"providerDidBegin:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1providerDidBegin(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"providerDidBegin:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didUpdate:for:)\/title","value":"pushRegistry:didUpdatePushCredentials:forType:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1pushRegistry(_:didUpdate:for:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushRegistry:didUpdatePushCredentials:forType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2c89a\/title","value":"provider:performPlayDTMFCallAction:"},{"op":"replace","path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2c89a\/fragments","value":[{"text":"- ","kind":"text"},{"text":"provider:performPlayDTMFCallAction:","kind":"identifier"}]}]}]}