{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CXProviderDelegate.provider(_:perform:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CXStartCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-2ig32"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-2ig32"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"metadata":{"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(im)provider:performStartCallAction:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","preciseIdentifier":"c:objc(cs)CXProvider","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"perform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CXStartCallAction","preciseIdentifier":"c:objc(cs)CXStartCallAction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"provider(_:perform:)","navigatorTitle":[{"text":"provider:performStartCallAction:","kind":"identifier"}],"modules":[{"name":"PushwooshVoIP"}],"role":"symbol","symbolKind":"method","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2ig32"},"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","kind":"symbol","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"role":"symbol","abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"title":"PushwooshVoIPImplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/provider(_:perform:)-2ig32":{"url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/provider(_:perform:)-2ig32","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/provider(_:perform:)-2ig32","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"provider:performStartCallAction:"}],"abstract":[],"title":"provider(_:perform:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider","text":"CXProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction","text":"CXStartCallAction"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"provider:performStartCallAction:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:performStartCallAction:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"provider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXProvider","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXProvider"},{"text":" *) ","kind":"text"},{"text":"provider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"performStartCallAction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CXStartCallAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CXStartCallAction"},{"text":" *) ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","op":"replace","value":"PushwooshVoIPImplementation"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/navigatorTitle","op":"replace","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2ig32\/title","op":"replace","value":"provider:performStartCallAction:"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1provider(_:perform:)-2ig32\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provider:performStartCallAction:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}