{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)"},"hierarchy":{"paths":[["doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"voipAppId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"externalID":"c:@M@PushwooshVoIP@objc(cs)PushwooshVoIPImplementation(cm)setPushwooshVoIPAppId:","modules":[{"name":"PushwooshVoIP"}],"roleHeading":"Type Method","role":"symbol","title":"setPushwooshVoIPAppId(_:)","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Sets the Pushwoosh VoIP Application Code.","type":"text"}],"references":{"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP":{"abstract":[{"text":"VoIP push notifications with native call UI for iOS applications.","type":"text"}],"url":"\/documentation\/pushwooshvoip","kind":"symbol","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP","role":"collection","title":"PushwooshVoIP"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation":{"identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation","kind":"symbol","navigatorTitle":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushwooshVoIPImplementation"}],"role":"symbol","abstract":[{"type":"text","text":"Orchestrates VoIP push notifications and CallKit integration for iOS applications."}],"title":"PushwooshVoIPImplementation"},"doc://com.pushwoosh.PushwooshVoIP/documentation/PushwooshVoIP/PushwooshVoIPImplementation/setPushwooshVoIPAppId(_:)":{"kind":"symbol","url":"\/documentation\/pushwooshvoip\/pushwooshvoipimplementation\/setpushwooshvoipappid(_:)","type":"topic","identifier":"doc:\/\/com.pushwoosh.PushwooshVoIP\/documentation\/PushwooshVoIP\/PushwooshVoIPImplementation\/setPushwooshVoIPAppId(_:)","navigatorTitle":[{"kind":"identifier","text":"setPushwooshVoIPAppId:"}],"abstract":[{"type":"text","text":"Sets the Pushwoosh VoIP Application Code."}],"title":"setPushwooshVoIPAppId(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPushwooshVoIPAppId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setPushwooshVoIPAppId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setPushwooshVoIPAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"voipAppId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/title","value":"PushwooshVoIPImplementation","op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/fragments","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation\/navigatorTitle","value":[{"text":"PushwooshVoIPImplementation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)\/title","value":"setPushwooshVoIPAppId:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setPushwooshVoIPAppId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pushwoosh.PushwooshVoIP~1documentation~1PushwooshVoIP~1PushwooshVoIPImplementation~1setPushwooshVoIPAppId(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}